"use client";

import { useEffect, useMemo, useState } from "react";

type Entry = { slug: string; title: string; time_complexity: string; space_complexity: string };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const estimate = (complexity: string, n: number) => ({ "O(1)": 3, "O(log n)": Math.ceil(Math.log2(n)), "O(n)": n, "O(n log n)": n * Math.ceil(Math.log2(n)), "O(n²)": n * n, "O(n³)": n ** 3, "O(2ⁿ)": 2 ** Math.min(n, 20), "O(n!)": n <= 10 ? Array.from({ length: n }, (_, i) => i + 1).reduce((total, value) => total * value, 1) : Infinity }[complexity] ?? n);

export function ComparisonWorkbench() {
  const [entries, setEntries] = useState<Entry[]>([]); const [first, setFirst] = useState(""); const [second, setSecond] = useState(""); const [size, setSize] = useState(16);
  useEffect(() => { fetch(`${api}/api/functions`).then((response) => response.json() as Promise<Entry[]>).then((items) => { setEntries(items); setFirst(items.find((item) => item.time_complexity === "O(n)")?.slug ?? items[0]?.slug ?? ""); setSecond(items.find((item) => item.time_complexity === "O(n²)")?.slug ?? items[1]?.slug ?? ""); }); }, []);
  const [a, b] = useMemo(() => [entries.find((item) => item.slug === first), entries.find((item) => item.slug === second)], [entries, first, second]);
  const sizes = [Math.max(2, Math.floor(size / 2)), size, Math.min(32, size * 2)];
  return <main className="app-shell compare-page"><nav className="nav"><a className="brand" href="/"><span className="brand-mark">↗</span> Complexity<br /><em>Library</em></a><div className="nav-links"><a href="/">Analyze</a><a href="/library">Library</a><a href="/algorithms">Algorithms</a></div><a className="nav-action" href="/#analyze">Analyze function <span>→</span></a></nav><header className="library-head"><p className="eyebrow">Comparison mode</p><h1>Same input.<br /><i>Different futures.</i></h1><p>Compare operation estimates from two published complexity signatures. These figures explain growth; they do not execute either function.</p></header><section className="compare-controls"><label>Function A<select value={first} onChange={(event) => setFirst(event.target.value)}>{entries.map((entry) => <option key={entry.slug} value={entry.slug}>{entry.title} — {entry.time_complexity}</option>)}</select></label><label>Function B<select value={second} onChange={(event) => setSecond(event.target.value)}>{entries.map((entry) => <option key={entry.slug} value={entry.slug}>{entry.title} — {entry.time_complexity}</option>)}</select></label><label>Reference input <input type="range" min="4" max="24" value={size} onChange={(event) => setSize(Number(event.target.value))} /><b>n = {size}</b></label></section>{a && b && <section className="compare-result"><div className="compare-head"><article><small>Function A</small><h2>{a.title}</h2><b>{a.time_complexity}</b></article><span>vs</span><article><small>Function B</small><h2>{b.title}</h2><b>{b.time_complexity}</b></article></div><table><thead><tr><th>Input</th><th>{a.time_complexity}</th><th>{b.time_complexity}</th></tr></thead><tbody>{sizes.map((n) => <tr key={n}><td>n = {n}</td><td>{estimate(a.time_complexity, n).toLocaleString()}</td><td className={estimate(b.time_complexity, n) > estimate(a.time_complexity, n) ? "larger" : ""}>{estimate(b.time_complexity, n).toLocaleString()}</td></tr>)}</tbody></table><p>The larger trace is highlighted at the selected input size. Change either function to compare a different growth pattern.</p></section>}</main>;
}
