"use client";

import { use, useEffect, useState } from "react";

type Detail = { id: string; slug: string; title: string; prompt?: string | null; code: string; language: string; time_complexity: string; space_complexity: string; confidence: number; analysis: { reasoning: string; assumptions: string[]; limitations: string[] }; visualization: { accessible_summary: string; type: string; operation_estimate: number } };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export function FunctionDetailView({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const [detail, setDetail] = useState<Detail | null>(null); const [state, setState] = useState("loading");
  useEffect(() => { fetch(`${api}/api/functions/${encodeURIComponent(slug)}`).then(async (response) => { if (response.status === 404) throw new Error("not-found"); if (!response.ok) throw new Error("error"); return response.json() as Promise<Detail>; }).then((value) => { setDetail(value); setState("ready"); }).catch((reason: unknown) => setState(reason instanceof Error ? reason.message : "error")); }, [slug]);
  if (state !== "ready" || !detail) return <main className="app-shell library-page"><nav className="nav"><a className="brand" href="/"><span className="brand-mark">↗</span> Complexity<br /><em>Library</em></a></nav><section className="library-state"><span className="empty-glyph">{state === "not-found" ? "?" : "⌁"}</span><h2>{state === "not-found" ? "That public function\ndoes not exist." : "Opening the\nfunction record."}</h2><p>{state === "not-found" ? "Published entries receive permanent links after moderation." : "Loading its analysis and visual explanation."}</p><a className="analyze-button library-cta" href="/library">Back to library <span>↗</span></a></section></main>;
  return <main className="app-shell detail-page"><nav className="nav"><a className="brand" href="/"><span className="brand-mark">↗</span> Complexity<br /><em>Library</em></a><div className="nav-links"><a href="/">Analyze</a><a href="/library">Library</a></div><a className="nav-action" href="/#analyze">Analyze function <span>→</span></a></nav><section className="detail-head"><p className="eyebrow">{detail.language} / public analysis</p><h1>{detail.title}</h1><div className="complexity-readout"><div><small>time</small><strong>{detail.time_complexity}</strong></div><div><small>space</small><strong>{detail.space_complexity}</strong></div><p>{Math.round(detail.confidence * 100)}%<span> confidence</span></p></div></section><section className="detail-grid"><article><p className="eyebrow">Why this scales</p><p className="reasoning">{detail.analysis.reasoning}</p><div className="visual-panel"><div className="visual-top"><span>visual model</span><span>{detail.visualization.type.replaceAll("_", " ")}</span></div><div className="detail-trace"><b>{detail.visualization.operation_estimate.toLocaleString()}</b><span>estimated operations<br />at the reference input</span></div><p>{detail.visualization.accessible_summary}</p></div>{detail.analysis.assumptions.length > 0 && <div className="assumptions"><b>Assumptions</b>{detail.analysis.assumptions.map((item) => <p key={item}>• {item}</p>)}</div>}</article><aside><p className="eyebrow">Source</p><pre><code>{detail.code}</code></pre>{detail.prompt && <><p className="eyebrow prompt-label">Original prompt</p><p>{detail.prompt}</p></>}</aside></section></main>;
}
